# Generated by Django 3.0.7 on 2020-06-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='downloaded',
            field=models.BooleanField(default=False, verbose_name='ダウンロード完了フラグ'),
        ),
    ]
