# Generated by Django 3.0.7 on 2020-06-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0004_auto_20200615_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficulty',
            name='bombs',
            field=models.IntegerField(default=0, verbose_name='ボムの数'),
        ),
        migrations.AddField(
            model_name='difficulty',
            name='obstacles',
            field=models.IntegerField(default=0, verbose_name='壁の数'),
        ),
        migrations.AlterField(
            model_name='difficulty',
            name='speed',
            field=models.IntegerField(default=0, verbose_name='スピード'),
        ),
    ]
