# Generated by Django 3.0.7 on 2020-06-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0005_auto_20200615_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficulty',
            name='bombs',
            field=models.IntegerField(verbose_name='ボムの数'),
        ),
        migrations.AlterField(
            model_name='difficulty',
            name='notes_per_sec',
            field=models.FloatField(default=0.0, verbose_name='NPS'),
        ),
        migrations.AlterField(
            model_name='difficulty',
            name='obstacles',
            field=models.IntegerField(verbose_name='壁の数'),
        ),
        migrations.AlterField(
            model_name='difficulty',
            name='speed',
            field=models.IntegerField(verbose_name='スピード'),
        ),
    ]
